# Language configuration
language: en_en # Possible values: en_en, ru_ru

# Enable join statistics
stats-enabled: true

# Default join messages
join-message:
  default: " &6Welcome,  &e%player% &6!"
  admin: " &cHello administrator  &e%player% &c!"
  moderator: " &aHello moderator  &e%player% &a!"

# Default quit messages
leave-message:
  default: " &c%player% left the server."
  admin: " &cAdministrator %player% left the server."
  moderator: " &cModerator %player% left the server."