name: CustomJoinMessagePlugin
version: 1.0.1
main: me.deadssilence.cjm.Main
api-version: 1.18
description: A plugin to customize join and quit messages for players.
commands:
  cjm:
    description: Manage join messages for groups and players.
    permission: cjm.admin
permissions:
  cjm.admin:
    description: Allows access to administrative commands for managing join messages.
    default: op